export const ERROR_CODES = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  MISSING_FIELDS: "MISSING_FIELDS",
  INVALID_ID: "INVALID_ID",
  INVALID_PHOTO: "INVALID_PHOTO",
  INVALID_FORMAT: "INVALID_FORMAT",
  PAYLOAD_TOO_LARGE: "PAYLOAD_TOO_LARGE",
  MALFORMED_JSON: "MALFORMED_JSON",

  AUTHENTICATION_REQUIRED: "AUTHENTICATION_REQUIRED",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  INVALID_TOKEN: "INVALID_TOKEN",
  ACCOUNT_UNVERIFIED: "ACCOUNT_UNVERIFIED",
  ACCOUNT_NOT_FOUND: "ACCOUNT_NOT_FOUND",
  ACCOUNT_DISABLED: "ACCOUNT_DISABLED",
  ACCOUNT_PENDING_VERIFICATION: "ACCOUNT_PENDING_VERIFICATION",
  REGISTRATION_REJECTED: "REGISTRATION_REJECTED",
  ACCOUNT_SUSPENDED: "ACCOUNT_SUSPENDED",
  ACCOUNT_DEACTIVATED: "ACCOUNT_DEACTIVATED",
  INVALID_ID_DOCUMENT: "INVALID_ID_DOCUMENT",
  REQUEST_ALREADY_PROCESSED: "REQUEST_ALREADY_PROCESSED",

  FORBIDDEN: "FORBIDDEN",

  PLATFORM_ACCESS_DENIED: "PLATFORM_ACCESS_DENIED",
  RESIDENT_WEB_ACCESS_DENIED: "RESIDENT_WEB_ACCESS_DENIED",
  PLATFORM_CONTEXT_MISMATCH: "PLATFORM_CONTEXT_MISMATCH",

  ROUTE_NOT_FOUND: "ROUTE_NOT_FOUND",
  NOT_FOUND: "NOT_FOUND",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  APPOINTMENT_NOT_FOUND: "APPOINTMENT_NOT_FOUND",
  MISSION_NOT_FOUND: "MISSION_NOT_FOUND",
  NOTIFICATION_NOT_FOUND: "NOTIFICATION_NOT_FOUND",
  REGISTRATION_NOT_FOUND: "REGISTRATION_NOT_FOUND",

  CONFLICT: "CONFLICT",
  DUPLICATE_RESOURCE: "DUPLICATE_RESOURCE",
  EMAIL_EXISTS: "EMAIL_EXISTS",
  ALREADY_VERIFIED: "ALREADY_VERIFIED",
  DUPLICATE_SCHEDULE: "DUPLICATE_SCHEDULE",
  SLOT_UNAVAILABLE: "SLOT_UNAVAILABLE",
  INVALID_STATUS_TRANSITION: "INVALID_STATUS_TRANSITION",
  TRIAGE_ORDER_VIOLATION: "TRIAGE_ORDER_VIOLATION",

  OTP_INVALID: "OTP_INVALID",
  OTP_EXPIRED: "OTP_EXPIRED",
  OTP_MAX_ATTEMPTS: "OTP_MAX_ATTEMPTS",
  OTP_COOLDOWN: "OTP_COOLDOWN",
  OTP_RATE_LIMITED: "OTP_RATE_LIMITED",
  INVALID_SESSION: "INVALID_SESSION",

  RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",

  DATABASE_ERROR: "DATABASE_ERROR",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
  EMAIL_SERVICE_LIMIT: "EMAIL_SERVICE_LIMIT",
  EMAIL_QUOTA_EXCEEDED: "EMAIL_QUOTA_EXCEEDED",
  EMAIL_CONFIGURATION_ERROR: "EMAIL_CONFIGURATION_ERROR",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",

  NETWORK_ERROR: "NETWORK_ERROR",
  TIMEOUT_ERROR: "TIMEOUT_ERROR",
  REQUEST_CANCELLED: "REQUEST_CANCELLED",
  INVALID_RESPONSE: "INVALID_RESPONSE",
  CLIENT_ERROR: "CLIENT_ERROR",
  UNKNOWN_ERROR: "UNKNOWN_ERROR",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export const SESSION_ENDING_CODES: string[] = [
  ERROR_CODES.AUTHENTICATION_REQUIRED,
  ERROR_CODES.TOKEN_EXPIRED,
  ERROR_CODES.INVALID_TOKEN,
  ERROR_CODES.ACCOUNT_NOT_FOUND,
  ERROR_CODES.ACCOUNT_UNVERIFIED,
  ERROR_CODES.ACCOUNT_DISABLED,
  ERROR_CODES.PLATFORM_ACCESS_DENIED,
  ERROR_CODES.RESIDENT_WEB_ACCESS_DENIED,
  ERROR_CODES.PLATFORM_CONTEXT_MISMATCH,
];

export const PLATFORM_DENIED_CODES: string[] = [
  ERROR_CODES.RESIDENT_WEB_ACCESS_DENIED,
  ERROR_CODES.PLATFORM_ACCESS_DENIED,
  ERROR_CODES.PLATFORM_CONTEXT_MISMATCH,
];
